steps:
  - label: ":toolbox:"
    if: |
      // This version is used for the default branch since
      // it uses the release version.
      build.branch == pipeline.default_branch
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    plugins:
      - docker#v5.7.0:
          image: "gusto/buildkite-builder:2.0.0"
          propagate-environment: true
  - label: ":toolbox:"
    if: |
      // This version is used for branch builds since
      // it uses the branch's code.
      build.branch != pipeline.default_branch
    commands:
      - "bundle"
      - "bin/buildkite-builder run ${BUILDKITE_PIPELINE_SLUG}"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    plugins:
      - docker#v5.7.0:
          image: "ruby:3.2.2"
          propagate-environment: true
